"""Добавлено поле info в таблицу user для технической информации

Revision ID: 983657770c40
Revises: 11991f7d05c6
Create Date: 2024-10-05 23:51:20.365623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983657770c40'
down_revision = '11991f7d05c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
