"""Modify promt table structure

Revision ID: fa02524ab60d
Revises: 983657770c40
Create Date: 2024-10-06 12:15:39.333020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa02524ab60d'
down_revision = '983657770c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('n_text', sa.String(length=4096), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promt', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
        batch_op.drop_column('n_text')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
